import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-screen">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark h-full flex flex-col`}
      >
        <header className="flex justify-center items-center py-8 px-4 border-b border-primary">
          <h1 className="text-3xl font-semibold highlighted-title">
            Text summarizer
          </h1>
        </header>
        <main className="flex items-center justify-center h-full">
          {children}
        </main>
      </body>
    </html>
  );
}
